name: comabem
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Atualizei para uma faixa mais comum e segura

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Ajustei para uma versão comum

# A seção a seguir é específica para Flutter.
flutter:

  # A linha a seguir garante que a fonte Material Icons seja incluída.
  uses-material-design: true

  # Para adicionar assets (imagens) à sua aplicação, adicione a seção 'assets'.
  # A indentação (espaçamento) é MUITO importante aqui.
  # A palavra 'assets:' deve ter dois espaços antes dela.
  # A linha '- assets/images/' deve ter quatro espaços antes dela.
  assets:
    - assets/images/

  # Exemplo de como adicionar fontes (deixe comentado se não for usar)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
